### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by leonardovida**
Fix readme by:
* Moving back images to man/figures as pkgdown requests
* Fixing h1 so that it appears on GitHub but not on the website
* Prepare for manual deployment of website to docs branch: github action building site deleted

### CODE REVIEW

**Comment by J535D165** [comment]
Can you explain why you are using an Rmd to render the README.md? Looks highly inefficient to me. 

> Prepare for manual deployment of website to docs branch: github action building site deleted

Why would you prefer a manual deployment?

**Comment by leonardovida** [comment]
> Can you explain why you are using an Rmd to render the README.md? Looks highly inefficient to me.

Because that's the only way I managed to have all the images on both GitHub and the pkgdown website working. 

> > Prepare for manual deployment of website to docs branch: github action building site deleted
> 
> Why would you prefer a manual deployment?

Because both me and @vankesteren had a lot of problems with the automatic mounting of the docs (e.g. failing for random reasons). So we decided to just push it manually.

What do you think about both?

**Comment by J535D165** [comment]
> Can you explain why you are using an Rmd to render the README.md? Looks highly inefficient to me.
> > Because that's the only way I managed to have all the images on both GitHub and the pkgdown website working.

Oke, I see this is common practice in the R ecosystem (e.g. ggplot2)...

> Because both me and @vankesteren had a lot of problems with the automatic mounting of the docs (e.g. failing for random reasons). So we decided to just push it manually.

What is the error? This pipeline triggers on main or master only and has run successfully last time.

**Comment by leonardovida** [comment]
> > Because both me and @vankesteren had a lot of problems with the automatic mounting of the docs (e.g. failing for random reasons). So we decided to just push it manually.
> 
> What is the error? This pipeline triggers on main or master only and has run successfully last time.

The action was already changed because of the tons of seemingly random errors it was throwing (mainly having to do with the connection to the remote OSM server)

**Comment by J535D165** [comment]
No, I don't understand. You are removing a file that only triggers at the main branch and has 1 contributor. https://github.com/sodascience/osmenrich/blame/develop/.github/workflows/pkgdown.yaml. As far as I can see, this action has never failed. So, what is causing those errors? Please point me to the specific errors, because I want to learn from them.

**Comment by leonardovida** [comment]
> So, what is causing those errors? Please point me to the specific errors, because I want to learn from them.

This action fails as sometimes when building the site, the public servers return an error caused by too many active connections on their side (not our fault). This makes the action fails. Given that there will not be many updates to the github pages website, me and @vankesteren thought about deleting the action and building the site manually

**Pull request merged**
